FROM rust:1.77-slim

WORKDIR /app
RUN apt-get update && apt-get install -y libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    file \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    llvm \
    clang \
    python3 \
    nodejs \
    npm

# Kurulum: Test, Coverage ve Mock API araçları
RUN cargo install cargo-nextest cargo-llvm-cov cargo-audit cargo-deny
RUN npm install -g json-server

COPY . .

# Test komutu (nextest)
CMD ["cargo", "nextest", "run", "--manifest-path", "src-tauri/Cargo.toml"]
